apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      version: "0.15.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    fullnameOverride: "cnpg"

    resources:
      limits:
        memory: 400Mi
      requests:
        cpu: 300m
        memory: 400Mi
