apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: kcdfrance
spec:
  forProvider:
    databaseVersion: POSTGRES_13
    region: europe-west9
    instanceType: CLOUD_SQL_INSTANCE
    maxDiskSize: 40
    settings:
      tier: db-custom-1-3840
      activationPolicy: ALWAYS
      availabilityType: ZONAL
      backupConfiguration:
        startTime: "04:00"
      dataDiskSizeGb: 10
      dataDiskType: PD_SSD
      ipConfiguration:
        privateNetworkRef:
          name: kcd
        requireSsl: true
      maintenanceWindow:
        day: 6
        hour: 23
        updateTrack: stable
      pricingPlan: PER_USE
      replicationType: SYNCHRONOUS
      storageAutoResize: true
  writeConnectionSecretToRef:
    name: kcd-cloudsql-connection-details
    namespace: crossplane-system
