apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: kcd
  labels:
    service: vpc
    creation: crossplane
spec:
  forProvider:
    autoCreateSubnetworks: false
    description: "Network used for experimentations and POCs"
    routingConfig:
      routingMode: REGIONAL
