apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - release.yaml
  - source.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cnpg-dashboard
    files:
      - ./dashboards/cnpg.json
    options:
      labels:
        grafana_dashboard: "1"
