apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBDIxZQEQ5N+yt3ukOaOWs53bnrpfD8NBV58LqgjStsLt+9piUA+33/fJ4IAm7Xxb/ZIRRkzfsdmNdcr3GbY2NIoy/hOyYoxJ9MBgbE4yWxY6OA1VOZDva2oxrQsm+0uHqjJfQKNXRbBhd5IY5qAH6UQKZFxXCIOB8+ETKYzixu+Zw7RIq+0LN6mwQq/wL+0xF7eQz/95kdT0eb8SSCYdoOx/mF35YvWn9Q5UBKV7Nd1clf1G80KKK5qXY5brTauBvpPjxjq0cyepVL+1EpMxa1C/ygAur1QqUa1VB6WYJgo9EMB0s750662jK+vokD1ecEL+784ouRyhGCrv/3l9tmkyyjE6J0ISJtJEGOcPKJ7yZR8pRZEF/3XCCjer5xpL5gsAo0ZI4qAEJVQtEiXVEOrCQSDOGVMch5bgrQXOemt4z9X+D6SfWt8Zab4/Qp+B+Lpw7Fom76vNFQDFLmWF9fu4UUo+KXrPdNhgC/XX2WYg/7y/c35f6Ukyvalc3P1TnLo8ShQ1M1QvNGf407ayBEouIVRFQ92QUFUfWC4KBORnlvXXg7wdi1ZDwMmUELh/8R3rmU1QgzVfkNS6xAh/5w3/+QdMOyaYRnjIc3OIOBHzMjenstgjvMpOw2JcZJFz/zEuh4kd7LryBVLQgTSOE9Mwdl7nW1r3sbcthmj7+dEeVP/GwS71RDNnl4N0NFUXgfitrXiljd0J9N06Ycf/8p1TKXbp8qlrhBUIg025haLw==
    admin-user: AgA5NSXYydICcaHp2ezjcb1UjICXsQpmN/vDpAcg6KTVJ+fPXSs6ffeetBFZNI9uYjOwKExQF1Fyb5m/Bp3MnGenyasC716UqN3tFhXURXLGZwlmAskiiA2wghHl5GQG3aA4xEnTBxJf1uPHxrsB7yeK07xTjpho+ZnbnlEoaRVBeVs3tbfcvXZ/GjIjwZOMPIQ82rAQrma8vibxgcSOMS7MXip/u2M+laLa3J0GqK1N+MmJ+UEm1F+8nnfIW9BvLyhwcP57mR7zKzWK3qEffHul9AntuI70H4l1sODqD/3H2imzCwWKbq3hKATx4863mIcR+txIWfNl1TjJHrv8ZcSbDMQ3lsVwhGer2lYKOCXNPUUs3qhSLzw/OnDPi54Ddm/lpIJP8mR4cJAeqboQBtA+jVvXXuWJz8tuSfQ9pCAobwepyqkGQzYS2XUL/GuSdfTL6cWkf6exbxln5vBfRFr4xnZONyOp3fdkEc1w9wGgJ/R5hbnR3yF6r6zF4DZ7VchXgIaigdYxlpTKVtmFt9JEK6tdkbjrfTAyjrrPIY1Qo1+j6A0QlExhPZXWpEOxWiq+Y1NbosK0QrQrU2ku/y9mRDdy/F9sey0m2LDdACmZpmeCzaGjqCKlA21EA7unuGo/jUsLcJRU2gunH+2d8u7V3JDTs/u1q/t/0UGg6ZD6FhwrzzEyhfefshVEGrDkg44ObdUK/Q==
  template:
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: observability
