apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBoCvj0hfNi5VoG+HnzLh3lO2iQBcR4sv6SrTT+pdv7800QbteScSBvk/Ak7jI2L3zzts8JgvVpwb0al4HUBPzEX3btxYIwUWbUK5znTCAcN7MBOLBXtg1r6XoDj/v3ow8kWroh0Ynmg2F5AmVyLra0pm/2irvjn5MGJh3ksNZhh91WNdFRi/dxAhnUBCVtbi47f9qIX4gy27YiQl6Tz5810gkZqn/0M0aogzfJOSD/3VslgW5wLmtJaC9GTKSCc58WhkVHhIpriV9Nt2egdB8pb6alePB0hVGSFcU7Qko6k2cmEBHRRMUy6zo/pUlMJlbMUxvqGZQ1y0ZSJPcWxCRbje7D4JDXzKwiY2dBy4u8SRARZmbVtwrliKLBkJb+bucHEC+VbnykXJLgD8Iy9a+pzufj6OiYRnU51IvN/YQ7dPa2BB9PRkmNZGyra+oatgUD+PkBjOpndhvte7uoWGnxpeDV6cYOvK+TngFXcT03VDIubbs8PDAx+jv2ygyr2lvKCz4N7EqAwbyX2vjDV1Cnq2Y5XtJTyeYCTkop+O5UO26jWoorbE8/cw1IvPIktsSPZjQRMziICI9G4pace+J4B1YUncR3UHM6HqaASpLN0MFOXgSEjuI4qboNgptXijAo6XItE+JSJWxI21XvEDVqgBMfikspsEQeIiDlav67voYkMVV2dKCG8QWl3j6TlHAlSn4Fyd5Roiah8aEFwEl/x/z0mMCQa9Y2PzuebjOOjA==
    admin-user: AgAUGQuAFh6sk4coQSmCjmvKsy9vdpgRsFU8wWscx1+aNe7+cO/TxmKEDgH4GZtnG3/Rdaa3qPpDmbd7Xlj+ZBoH2bqYqChsGgWW3aJJvXI8U4ETHaOiE73yu+JsHg0dgpDQ3eVvzFz/92URX4hNrUCRxnACEP1YuHgOvIb2fWz8qOO0uZZG01TmR/Am4wl2Db9zY3kFS71hxrhj30k0uz7qnB6dD722HRxx+UjS+oDwHmFTXlngH9Vpro4KWhNKQxv+Zmr59Oysf1uu+XfQrcYohyKODP7fLxg2WGhwEoC29dT51h0frJ1iJ000a9eNPqFRBm4Bihv0lBl5e0gLSA75DoYYoWflDfeFDvz6kyRT1bush9v6WpJxHCiA5LyYwZ0azUCnvXH9METWmCB3lFw3BPChaWZvQj5sbPgm0H7oJ2xDgvCBFYDbduiAcTd6slrmsDWMeHBEnFRyR0u/i0TpuVAYYXQHJG4tg6VUpDxFuLVeJFNClwUJGWzB/12yBHX7UeZz2z2jzFUZB1qBbN0Qjq2V3RVOElV9SX1C2G6rUYELse5QGfXldOfEzu1UQXlVnWSUcl/rz17om9wmxJuSq2nsrofIaI4gOuGODUReN32pNR6Nv+m1ihWPli68lNMFzQLtsfBTosLMhWM1P58h8WilMzI/Qxds5lQN8fAJfkYQ22amawkBDSw1OrvRUf081aVI5w==
  template:
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: observability

